sudo: required

language: php

services:
  - mysql

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.npm

env:
  global:
    - EE_VERSION=master
    - WP_VERSION=latest WP_MULTISITE=0

before_install:
   - nvm install && nvm use
   - npm install npm -g
   - |
      if [[ "$SKIP_XDEBUG_REMOVE" != "true" ]]; then
        cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
        phpenv config-rm xdebug.ini
        echo "xdebug removed";
      fi

before_script:
  - bash tests/bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - . tests/bin/setup-addon-tests.sh
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    # Install the specified version of PHPUnit depending on the PHP version:
    if [[ -n "$TRAVIS_PHP_VERSION" ]]; then
      case "$TRAVIS_PHP_VERSION" in
        7.3|nightly)
          # when wp tests support phpunit 7 we'll update this.
          echo "Using PHPUnit 6"
          composer global require "phpunit/phpunit=6.5.*"
          ;;
        7.2|7.1|7.0)
          echo "Using PHPUnit 6"
          composer global require "phpunit/phpunit=6.5.*"
          ;;
        5.6|5.5)
          echo "Using PHPUnit 4.8"
          composer global require "phpunit/phpunit=4.8.*"
          ;;
        *)
          echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
          exit 1
          ;;
      esac
    fi
  - mysql --version
  - phpunit --version
  - phpenv versions
  - npm --version
  - node --version

script: npm run test-php

jobs:
  fast_finish: true
  allow_failures:
    - php: nightly
    - php: 7.3
      env:
        - PHP_LINT=1
        - PHP_LINT_WITH_WARNINGS=yes
  include:
    - stage: test
      php: 7.3
      env:
        - PHP_LINT=1
        - PHP_LINT_WITH_WARNINGS=no
      script:
        - composer install || exit 1
        - composer config-eventespressocs || exit 1
        - npm run lint-php:skip-warnings || exit 1
    - php: 7.3
      env:
        - PHP_LINT=1
        - PHP_LINT_WITH_WARNINGS=yes
      script:
        - composer install || exit 1
        - composer config-eventespressocs || exit 1
        - npm run lint-php || exit 1
## skipping for now because there's no javascript to test!
#    - env:
#        - JAVASCRIPT_TESTS=1
#      language: node_js
#      node_js:
#        - node
#        - nvm install && nvm use
#        - npm install npm --latest-npm
#      script:
#        - npm run ci || exit 1
    - language: node_js
      env:
        - LICENSE_CHECK=1
      script:
        - npm run lc || exit 1
    - php: 7.3
    - php: 7.2
    - php: 7.1
    - php: 7.0
    - php: 5.6
    - php: 5.5
    # multisite
    - php: 7.2
      env: WP_MULTISITE=1
    # wp 4.5 builds
    - php: 5.6
      env: WP_VERSION=4.5
    - php: nightly

notifications:
  slack:
    rooms:
      secure: "vxP+dAhK+UtmvJ5Pa1zh9hIrqnRoQA1mqDS74CFLSXVZf9m9TgGLNnKF05WxZohOOKaZwzHSvWgcGIUmhy/p3SOet8IQCfolAtLIytEQV1QrZTY0ePJ/mAgiN3LKVuQW/o8tWjKutjieN1CN+/KL4eJ34KCt4vsAM/8NUHhVrKllGLsAxsjg/Xb/6sSqKqdLMUeMv4wAv3GZjkGiBK12ndHoJde5wbzuXT/e2NMAvEFHnoOQvuzSvRkK+zNOzW3P1ThRTPGKlSDZTWMMql4996LSTA7txhzTl78fswU3G3V/8IzPfU49RBNZQaTDib7ufijt/CtNYpnspVRekfWqhv09hzWvxzzOREpIIJFak31v8d+hshyh4hKZ8FsuIR+TrBliq/jZOFTuje8OJ6ISxI7B42PUIvkAVgZ0QFThTLdx0JfYavvb2gcp1dExZC62CfBg/KyYy/I1WRRApOeESvQoh5qu7R7xox+ACfYImfHfSFQfQk+gBUURUI3z2TVJmiMKR/5buwEHzkLNOY6oj8D8AAMgKczS3FynQB/3PnPLUcI98FMtQJERv/2ehhDYm6tNzaV0Lnwy7Gegl3UCQFsEp55Y6Qm4Dc3Lg5vzmbNvbjOMXmoD5pBOp/Eu6GwI4C5jdjKl0J6oksFCEigHj2iBhxhEQfEO3V9l2wPvABo="
    on_success: change
    on_failure: always
    on_start: always
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository}@%{branch} by %{author} %{result} in %{duration}"
      - "%{commit_message}"
